[package]
name = "ws-segment-rs-napi"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Node-API bindings for ws-segment-rs"

[lib]
name = "novel_segment_napi"
crate-type = ["cdylib"]

[dependencies]
ws-segment-rs = { workspace = true }
napi = { version = "2.16", default-features = false, features = ["napi4"] }
napi-derive = "2.16"

[build-dependencies]
napi-build = "2.1"
